name: utn-test-manual
on:
    workflow_dispatch:
jobs:
  utn-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          spec: cypress/e2e/auto-practice1/
          browser: chrome
      - name: upload
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress-videos
            path: cypress/videos
            retention-days: 2
        env:
          # pass the Cypress Cloud record key as an environment variable
          PASS_ONE: ${{ secrets.PASS_ONE }}
